### ISSUE TITLE
Feedback for HW 8

### ISSUE THREAD

**Issue by MaksHostroushko** [EduardKurbanov/RubyHW#16]
Looks good!
Clear code with pagination and serializer
Let's add some improvements

1. https://github.com/EduardKurbanov/RubyHW/blob/main/HW8/Rails_Api/app/controllers/api/v1/articles_controller.rb#L11..L12
You do the same twice here. Please, don't use the useless scope here

2. https://github.com/EduardKurbanov/RubyHW/blob/main/HW8/Rails_Api/app/controllers/api/v1/articles_controller.rb#L13
Please, rename this scope. First of all, the name is not describe the sense of this action. Also, the name is too long

3. https://github.com/EduardKurbanov/RubyHW/blob/main/HW8/Rails_Api/app/controllers/api/v1/articles_controller.rb#L14
Please, move this logic to `self.method`
Also, name is too long

4. https://github.com/EduardKurbanov/RubyHW/blob/main/HW8/Rails_Api/app/controllers/api/v1/articles_controller.rb#L16
I believe this scope is over logic. We don't need to move this order to specific scope
Let's order articles in controller without scope

**Comment by EduardKurbanov** [comment]
поправил
