### ISSUE TITLE
Feedback HW9

### ISSUE THREAD

**Issue by LVALL** [EduardKurbanov/RubyHW#17]
1) Дубльований опис PUT/PATCH методів в обох контролерах. Почитайте додатково про відмінність цих методів [тут](https://www.abstractapi.com/guides/put-vs-patch#:~:text=PUT%20and%20PATCH%20both%20perform,entire%20body%20in%20the%20request.)

2) Пропущений опис для методу show Articles контролера.

3) Метод /update_status для обох контролерів, описаний як GET-метод. Метод GET існує для отримання інформації і ніколи для її модифікації не повинен використовуватись. Детальніше про методи [тут](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods)

4) У коді не повинно бути кирилиці, якщо це не текст в локалях, тому, будь ласка, пишіть описи до документації англійською!

**Comment by EduardKurbanov** [comment]
поправил.
