### ISSUE TITLE
HW3(task6-7) review

### ISSUE THREAD

**Issue by Aztec0** [EduardKurbanov/RubyHW#2]
В цілому все чудово, але деякі нюанси:
1. Додати в "readme" інструкцію по встановленню
2. Змінити в "task2.rb" змінні (arg_t, a_1, pl_count) і подібні на більш зрозумілі/осмислені, покращить читання коду.
3. Перевірити код rubocop, зробити корекції
4. Дописати метод який би виводив те що ми можемо робити з улюбленцем, не зручно гортати в початок, щоб переглянути яка цифра відповідає за яку дію
5. Можна зробити щоб html файл генерувався автоматично, не зручно кожен раз викликати команду щоб перезаписати файл.

**Comment by EduardKurbanov** [comment]
сделано.

**Comment by Kashoid23** [comment]
Хороша робота 🚀 

- [x] Коли ви використовуєте атрибут attr_reader, це означає, що ви можете звертатись до атрибута екземпляра без використання змінної екземпляра

```
class Pet < ElectronicAnimal
  attr_reader :name
  
  puts "ви гуляєте з #{name}"
  instead
  puts "ви гуляєте з #{@name}"
```

- [x] Використайте константу для масиву з статичним текстом

```
food_argument = 'я хочу їсти'
    toilette_argument = 'я хочу в туалет'
    argument_walk = 'я хочу гулять'
```

- [x] random_s - текстовий масив, чи є сенс конвертувати їх повторно в стрінг?

`random_s.to_s`

- [x] Якщо методи не визначені в області protected/private вони за замовчуванням публічні, не потрібно додатково оголошувати

`public`

- [x] Використайте https://apidock.com/ruby/Array/include%3F щоб спростити код

`if el_animal == 'dog' || el_animal ==  'cat' || el_animal == 'parrot'`

- [x] Є повторюваність, це суперечить одному з головних принципів руб Don't Repeat Yourself (DRY), подумайте як це виправити

`puts '*' * 50 `

**Comment by EduardKurbanov** [comment]
1, поправил.
2, поправил,
3, поправил.
4, поправил,
5, поправил, 
6, поправил,

**Comment by Kashoid23** [comment]
@EduardKurbanov random_s та animal_choice_arg мають бути константами. Потрібно допрацювати!

**Comment by EduardKurbanov** [comment]
все поправил.

13 ноября 2022, 15:06:52, от "Vitalii Kashoid" ***@***.***>:


@EduardKurbanov random_s та animal_choice_arg мають бути константами. Потрібно допрацювати!
