### ISSUE TITLE
Feedback HW2 task 1

### ISSUE THREAD

**Issue by MaksHostroushko** [EduardKurbanov/RubyHW#3]
Looks great!
But let's add some improvements

General fix: please, read [code style](https://github.com/rubocop/ruby-style-guide) rules add refactor your code
For example, add the correct spaces

1 `arr.select {|i| i.even?}`
First of all, we need to add spaces inside `{ }` 
Also, we need to use an alias for this block
I mean, `arr.select(&:even?)`

2.`arr.select { |i| i <= 26 && i >= 1 }`
It works and looks good
But we have ruby method for this case
`arr.select { |element| element.between?(1, 26) }`

**Comment by EduardKurbanov** [comment]
все исправил

**Comment by EduardKurbanov** [comment]
все исправил
