### ISSUE TITLE
Feedback HW2 task 2

### ISSUE THREAD

**Issue by MaksHostroushko** [EduardKurbanov/RubyHW#4]
Looks good!
Let's add some changes

1. You can write this code in a single line
I mean
`@sleep_t = 0 if @sleep_t >= 10` 
instead of
```
if @sleep_t >= 10
  @sleep_t = 0
  end
```

2. https://github.com/EduardKurbanov/RubyHW/blob/main/HW2/task2.rb#L10..L20
Please, don't use `case` without `else` option

3. https://github.com/EduardKurbanov/RubyHW/blob/main/HW2/task2.rb#L26
Why do you use `super` here??
I think it's useless code

4. https://github.com/EduardKurbanov/RubyHW/blob/main/HW2/task2.rb#L62..L67
Please, add `else` option here

5. Please, try to use understandable names for the variables. For example, `ran_b` is an incorrect one

6. `@hunger >= 5 &&  @hunger <= 6`
Please, try to optimize your logic
For example, in this case, we just can write `@hunger == 5 || @hunger == 6`

**Comment by EduardKurbanov** [comment]
все исправил

**Comment by EduardKurbanov** [comment]
поправил
