### ISSUE TITLE
Feedback HW 5

### ISSUE THREAD

**Issue by LVALL** [EduardKurbanov/RubyHW#6]
- ви створили коректний колбек-метод `set_article`, але не розібрались з його використанням та не використали його з коректним фільтром.

- [x] Почитайте докладніше [тут](https://edgeguides.rubyonrails.org/action_controller_overview.html#filters) та спробуйте додати коректний фільтр з викликом вашого методу  `set_article` лише для потрібних методів. Після чого позбудьтесь дублювання 
https://dannemanne.com/posts/ruby_on_rails_explained_before_action. Після чого приберіть дублювання `@article = Article.find_by(id: set_article)` та проаналізуйте, що ви робили у цій строці та чому це не правильно

- [x] `@article = Article.new(title: article_params[:title], body: article_params[:title])` 
по-перше в body та title передано article_params[:title]. - будьте уважніше
по-друге якщо ви можете взяти значення за ключем, чому б відразу не зробити `@article = Article.new(article_params)`  ?

Поексперементуйте та дайте відповідь на це питання.

- [x] статуси до респонзів додано вибірково. На методі `show` та `update` вони відсутні, хоча повинні там бути

- [x] для методу `destroy` в якості статусу при вдалому видаленні передають статус `:no_content`, а для негативного кейсу - `:unprocessible_entity` 
- Детальніше про статус-коди 
https://guides.rubyonrails.org/layouts_and_rendering.html#the-status-option

- Детальніше про рендерінг 
https://guides.rubyonrails.org/layouts_and_rendering.html

- [x] Почитайте про контролери детальніше тут: https://guides.rubyonrails.org/action_controller_overview.html

**Comment by EduardKurbanov** [comment]
исправил все замичания.
