### ISSUE TITLE
Feedback HW6

### ISSUE THREAD

**Issue by setwith** [EduardKurbanov/RubyHW#7]
Код працює, по його роботі нарікань немає. Всі реквести API обробляє коректно.

- [x] Можна вдосконалити ініціалізацію проекту добавивши в файл seed.rb (тоді не потрібно буде створювати обєкти в бд вручну. При створенні творенні бази даних відразу будуть створюватись об'єкти в ній.
Реалізувати можна таким чином:
```ruby
Article.create([
                 {
                   title: 'First article',
                   body: 'Some text for article'
                 },
                 {
                   title: 'Second one',
                   body: 'Some more text for article'
                 }
                 ])
```

- [x] Варто додати _database.yml_ в .gitignore та створити замість нього _database.yml.example_

- [x] Не вдалось оновлювати статус коментаря, змінити його значення на опублікований. (Можливо помилка на моїй стороні 🙂)

**Comment by EduardKurbanov** [comment]
все поправил.
